name: Compile LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: article.tex
      - name: Upload compiled document as artifact
        uses: actions/upload-artifact@v2
        with:
          name: article.pdf
          path: article.pdf
