name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            article.tex
            cover_letter.tex
      - name: Upload compiled documents as artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            article.pdf
            cover_letter.pdf